services:
  web:
    build: .
    command: gunicorn finance_project.wsgi:application --bind 0.0.0.0:8000 --timeout 120 --workers 2
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"

