# Generated by Django 5.1.2 on 2024-10-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("financial_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockdata",
            name="predicted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
